version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
  server:
    build: .
    image: swagger-sample
    ports:
      - "3000:3000"
    volumes:
      - ./:/go/src/github.com/furiko/swagger-sample/server